Repository Saqi-CS/Modern-Landing-Page, pull requests merged in 2022-10, with the labels that each got.

#2 Build a header section
  public/index.html
Labels: hacktoberfest-accepted

#3 Added a content section in a site.
  public/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#4 Added the image and rounded rectangle.
  public/index.html
Labels: good first issue, hacktoberfest-accepted

#5 Create Readme.md
  Readme.md
Labels: hacktoberfest-accepted

#6 Add New Section
  public/index.html
Labels: hacktoberfest-accepted

#7 Add button
  public/index.html
Labels: hacktoberfest-accepted

#8 Added the Card section
  public/index.html
Labels: hacktoberfest-accepted

#9 Added Addition Card section in site
  public/index.html
Labels: hacktoberfest-accepted

#10 Added the FAQ section
  public/index.html
Labels: hacktoberfest-accepted

#11 Added the contact pus age
  public/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#12 updated the footer
  public/index.html
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#13 Updated the footer and faq section
  public/index.html
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#14 added the card section
  public/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#15 Improving code style with prettier
  package-lock.json
  package.json
  public/index.html
  public/style.css
  src/styles.css
  tailwind.config.js
Labels: hacktoberfest-accepted
